#! /bin/bash

if [ $# -ne 3 ]; then
	exit 1
fi

verbose=0
perform=1

src_dir="$1"
dst_dir="$2"
path="$3"
src_path="$src_dir/$path"
dst_path="$dst_dir/$path"

if [ -d "$src_path" ]; then
	if [ ! -d "$dst_path" ]; then
		if [ "$verbose" -ne 0 ]; then
			echo "mkdir -p $dst_path"
		fi
		if [ "$perform" -ne 0 ]; then
			mkdir -p "$dst_path" || panic "cannot make directory"
		fi
	fi
else
	if [ ! -e "$dst_path" ]; then
		if [ "$verbose" -ne 0 ]; then
			echo "ln -s $src_path $dst_path"
		fi
		if [ "$perform" -ne 0 ]; then
			ln -s "$src_path" "$dst_path" || panic "cannot make link"
		fi
	fi
fi

